### ISSUE TITLE
TB3 activation for 5K display

### ISSUE THREAD

**Issue by Hochiss** [M82589933/ThinkPad-X1-Yoga-3rd-Hackintosh#1]
I am following the discussion at [ tylernguyen /
x1c6-hackintosh ](https://github.com/tylernguyen/x1c6-hackintosh/issues/24), trying different ssdt-tbs.aml patches to make my LG5K light up via TB3 port.  You [mentioned](https://github.com/tylernguyen/x1c6-hackintosh/issues/24#issuecomment-678764314):

" _the kexts made by @CrazyPegasus is attached below. In theory, X1C6 can apply it with no error since there are so many similarities between X1Y3 and X1C6.
[TB3Patch-Crazy.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/5113884/TB3Patch-Crazy.zip)_"

I applied the SSDT-X1Y3.aml (from the linked zip) only, it seems for my X1C6 the most promising solution (yet not light up LG5K display);  The results as following(BIOS TB3 assistant mode **disabled**):

- Boot with closed lid, cannot light-up LG5K;
- After boot, open lid, native LCD can light up, after login I found although LG5K is not light up, its webcam/Audio/Hub all accessible, yet if hotplug then lose them; ( it sounds like TB3 is working, only LG5K is not supported):
- under SysPre/PCI, TB's 3 compoents listed:
![image](https://user-images.githubusercontent.com/36304198/92609125-8191b100-f2b6-11ea-9f20-bdc58b76e18a.png)
- IOreg:
![image](https://user-images.githubusercontent.com/36304198/92609474-e5b47500-f2b6-11ea-9d80-d5fe4fbc7e4d.png)

-------
**Question:**

- Any ideas why LG5K not light up? 
  (PS: if I use a USB-C/USB3.1 cable, both native & LG5K can light up without any patches, but LG5K only 2K not 5K)
- MacBookPro 14,1 said to be able to single max. 5K; yet I closed the lid boot not able to light up; does this matter?
- What is in fact the most essential in ssdt patches, in order to activate TB3? (hotplug at next?)

Thanks!

-----
X1C6, HDR2K, macOS 10.15.6, MacBookPro 14,1

**Comment by EigenTom** [comment]
Sorry, I could not test the USB-C output functionality because I could not find a 4K display for testing. I noticed that @CrazyPegasus has already provided a possible solution to this problem. Could you please tell me whether that method work for you or not? Thank you.

**Comment by Hochiss** [comment]
unfortunately, it doesn't work for me with the hotpatch w.r.t. AppleGraphicsDevicePolicy(AGDP) as mentioned by @CrazyPegasus: 

> "_This has something to do with the AppleGraphicsDevicePolicy driver of macOS. It is recommended to add a patch to try using OC boot, as shown below:_"

> ![12](https://user-images.githubusercontent.com/38367520/92886183-0828c880-f446-11ea-82b5-f8acc0a92b78.png)

Before I tell my investigation, Let me make it short: I am doubting the issue (LG5K couldn't light up) is related to TB3, because I tried a LG 4K(USB-C) monitor, which is also not able to get 4K but only 2K too(like LG5K);

Here is my investigation: 
( My HW: X1C6, HDR2K, macOS 10.15.6, MacBookPro 14,1, UHD620 as 0x591B0000 cf.: [Rehabman's github config.plist](https://github.com/RehabMan/OS-X-Clover-Laptop-Config))

### 1. Cannot find AGDP with board-id and its config/restriction thus patch `BA000000 00` no found?
 following the [AppleGraphicsDevicePolicy patch thread at tmx86](https://www.tonymacx86.com/threads/what-does-this-patch-do-to-applegraphicsdevicepolicy.272271/): 

> "... When using a SMBIOS that uses AppleGraphicsDevicePolicy, it tells the OS what graphics configuration to use .."

I searched `/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext` with my MacBookPro 14,1's [board-ID: Mac-B4831CEBD52A0C4C](https://webcache.googleusercontent.com/search?q=cache:Te6WHs4ltkwJ:https://mrmacintosh.com/list-of-mac-boardid-deviceid-model-identifiers-machine-models/+&cd=1), but cannot find the board-ID! : ( so that the patch does nothing)
![image](https://user-images.githubusercontent.com/36304198/93722383-b21afa00-fb96-11ea-9e34-adb46eb12570.png)
(this picture is same as [above mentioned thread](https://www.tonymacx86.com/threads/what-does-this-patch-do-to-applegraphicsdevicepolicy.272271/post-1914236)) 

means MacBookPro 14,1 has no AGDP restriction, thus patch not working? 

### ig-platform-id matters? 

- My config.plist applied with ig-platform-id UHD620 as 0x591B0000 cf.: [Rehabman's github config.plist](https://github.com/RehabMan/OS-X-Clover-Laptop-Config);
- but I  notice your X1Y3( similar HW/spec. with UHD620) as [0x59160000](https://github.com/KirisameMarisaa/ThinkPad-X1-Yoga-3rd-Hackintosh/tree/master/EFI-OC%200.6.0/EFI-No%20BIOSMod/OC); 
- As exactly the same HW/spec, @tylernguyen is using [0x5927 0004](https://github.com/tylernguyen/x1c6-hackintosh/tree/master/EFI-OpenCore/EFI/OC)?
- Windows 10 report( also Clover boot.log) reports UHD620's platform is 0x5917 8086

Does the ig-platform-id matter?

**Comment by Hochiss** [comment]
(_Since I don't have the 5K anymore, and I have now a 4K same issue. It seems OP issue is about [DMVT memory allocation](https://github.com/tylernguyen/x1c6-hackintosh/issues/40#issuecomment-659370165)._)

Solved! I adapted the OC's config.plist to Clover's config.plist.
https://github.com/tylernguyen/x1c6-hackintosh/issues/40#issuecomment-698456353

- change ig-platform-id to 0x5927 0004; 
- disable KextsPatch's old Framebuffer patchs for 0x591B 0000; 
- add : 

```xml			
                       <dict>
				<key>Comment</key>
				<string>KBL-DVMTpatch-10.15.4 (Enable 4K UHD HDMI/DisplayPort Output)</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				D4KPAwAA
				</data>
				<key>InfoPlistPatch</key>
				<false/>
				<key>Name</key>
				<string>com.apple.driver.AppleIntelKBLGraphicsFramebuffer</string>
				<key>Replace</key>
				<data>
				D4IAAAAA
				</data>
			</dict>
```

- and in Device section add Properties:

```xml			
                       <dict>
				<key>Comment</key>
				<string>4K disaply</string>
				<key>Device</key>
				<string>PciRoot(0x0)/Pci(0x2,0x0)</string>
				<key>Key</key>
				<string>framebuffer-fbmem</string>
				<key>Value</key>
				<data>
				AACQAA==
				</data>
			</dict>
			<dict>
				<key>Comment</key>
				<string>4K display</string>
				<key>Device</key>
				<string>PciRoot(0x0)/Pci(0x2,0x0)</string>
				<key>Key</key>
				<string>framebuffer-stolenmem</string>
				<key>Value</key>
				<data>
				AAAwAQ==
				</data>
			</dict>
```

- rebuild cache


![Screenshot 2020-09-24 at 18 32 23](https://user-images.githubusercontent.com/36304198/94176197-09231680-fe98-11ea-8353-ecf04e7e663a.png)
