### ISSUE TITLE
Advanced menu of the BIOS

### ISSUE THREAD

**Issue by WuMay** [M82589933/ThinkPad-X1-Yoga-3rd-Hackintosh#3]
How can I unlock the BIOS Advanced menu . The URL 404

**Comment by EigenTom** [comment]
具体的详细教程详见:
https://blog.csdn.net/u010186354/article/details/107700600

类似的操作视频如下: (挂梯子)
https://www.youtube.com/watch?v=ce7kqUEccUM

BTW: 目前X1Y的EFI Patch还有数个问题, 包括0D/6D Patch没完全生效, USB Port定制尚未完美等. 这段时间比较忙, 十二月左右会有一次较大的功能性更新, 解决这些问题.

**Comment by WuMay** [comment]
谢谢啦 等更新
